Azure/meta-azure-service-broker

- README.md
- docs/contribution-guide.md
- docs/how-admin-deploy-the-broker.md
Recommendations for minor corrections/improvements to some of the documentation items
> Correction of minor typos in documentation

- package.json
- test/integration/lifecycle.js
- test/utils/azuredocdbClient.js
- test/utils/azurerediscacheClient.js
- test/utils/azureservicebusClient.js
- test/utils/azurestorageblobClient.js
- test/utils/clients.js
- test/utils/statusCode.js
Add end to end test for services
1. azuredocdb
2. azurerediscache
3. azureservicebus
4. azurestorageblob
The test will try to validate the serivce that is just created:
1. make sure the serivce is created
2. make sure the service credential offered by broker is workable
> Add end to end test for services

- docs/azure-document-db.md
- docs/azure-redis-cache.md
- docs/azure-sql-db.md
- lib/services/azuredocdb/service.json
- lib/services/azurerediscache/service.json
- lib/services/azuresqldb/client.js
- lib/services/azuresqldb/service.json
- test/unit/services/azuresqldb/provision-spec.js
fixup service plan names & descriptions, free/paid awareness, retries on REST requests, bug with sql server provisioning + firewall
> various fixes to redis, docdb, sqldb

- docs/how-admin-deploy-the-broker.md
- lib/common/index.js
- lib/common/resourceGroup-client.js
- lib/services/azurerediscache/client.js
- lib/services/azureservicebus/index.js
- lib/services/azureservicebus/utils.js
- lib/services/azuresqldb/client.js
- lib/services/azurestorageblob/storageblobclient.js
- package.json
- test/unit/common/utils-tests.js
The following service brokers are supported both in `AzureCloud` and `AzureChinaCloud`.
* DocumentDB Service
* Event Hub Service
* Redis Cache Service
* Service Bus Service
* Storage Blob Service
* SQL Database Service
> Support multiple environments

- .cfignore
- docs/azure-document-db.md
- docs/azure-redis-cache.md
- docs/azure-service-bus.md
- docs/azure-sql-db.md
- docs/azure-storage-blob.md
- docs/how-admin-deploy-the-broker.md
- examples/documentdb-example-config.json
- examples/rediscache-example-config.json
- examples/servicebus-example-config.json
- examples/sqldb-example-config.json
- examples/storageblob-example-config.json
- lib/broker/db/sqlserver/index.js
- lib/broker/db/sqlserver/sqlserver.js
- lib/broker/v2/api-handlers.js
- lib/services/azurerediscache/cmd-provision.js
- lib/services/azureservicebus/index.js
- lib/services/azureservicebus/utils.js
- lib/services/azurestorageblob/index.js
- package.json
- test/integration/test-matrix.js
- test/unit/services/azureservicebus/provision-spec.js
- test/unit/services/azurestorageblob/bind-spec.js
- test/unit/services/azurestorageblob/provision-spec.js
1. Add example json with parameters description for all the brokers.
2. Add retry for sql database operations. Fix #3.
3. Remove default parameters in storage blob service and service bus service.
4. Fix errors callback and add callback function to throw them out.
5. Update unit tests and integration tests for new changes.
> add example json files for all the brokers and fix some bugs

- lib/common/index.js
- lib/services/azurerediscache/cmd-provision.js
- lib/services/azureservicebus/index.js
- lib/services/azureservicebus/utils.js
- lib/services/azuresqldb/client.js
- lib/services/azurestorageblob/index.js
- test/integration/test-matrix.js
- test/unit/services/azureservicebus/provision-spec.js
- test/unit/services/azuresqldb/provision-spec.js
- test/unit/services/azurestorageblob/index-spec.js
- test/utils/clients.js
Add tags for the following services:
* azure-storageblob
* azure-servicebus
* azure-rediscache
* azure-sqldb
> Add tags for services

- docs/azure-sql-db.md
- lib/common/index.js
- lib/services/azureservicebus/index.js
- lib/services/azureservicebus/utils.js
- lib/services/azuresqldb/client.js
Service bus:
- Config will be rewritten in previous code.
Sql database:
- Failed creating does not return error, the broker should check status code.
> Fix config passing issue in service bus; fix sql database creating issue

- lib/services/azuredocdb/client.js
- lib/services/azuredocdb/cmd-provision.js
- lib/services/azurerediscache/client.js
- lib/services/azureservicebus/index.js
- lib/services/azureservicebus/utils.js
- lib/services/azuresqldb/cmd-provision.js
- lib/services/azurestorageblob/index.js
- lib/services/azurestorageblob/storageblobclient.js
- test/unit/services/azureservicebus/poll-spec.js
- test/unit/services/azureservicebus/provision-spec.js
- test/unit/services/azurestorageblob/index-spec.js
- test/unit/services/azurestorageblob/provision-spec.js
To avoid the broker using an already existed resource on Azure.
> check resource availability before provisioning

- lib/broker/v2/api-handlers.js
Always return CC with `200 OK`. If there is an error, the `state` in the response body will be `failed`.
> Update the polling operation

- docs/how-admin-deploy-the-broker.md
- lib/broker/db/sqlserver/index.js
- lib/common/encryptionhelper.js
- lib/common/index.js
- lib/services/azuredocdb/cmd-bind.js
- lib/services/azuredocdb/cmd-poll.js
- lib/services/azuredocdb/index.js
- lib/services/azurerediscache/client.js
- lib/services/azurerediscache/cmd-bind.js
- lib/services/azurerediscache/cmd-poll.js
- lib/services/azurerediscache/cmd-provision.js
- lib/services/azurerediscache/index.js
- lib/services/azuresqldb/client.js
- lib/services/azuresqldb/cmd-bind.js
- lib/services/azuresqldb/cmd-poll.js
- lib/services/azuresqldb/index.js
- test/integration/test-matrix.js
- test/unit/common/utils-tests.js
- test/unit/services/azuredocdb/bind-spec.js
- test/unit/services/azuredocdb/index-spec.js
- test/unit/services/azuredocdb/poll-spec.js
- test/unit/services/azurerediscache/bind-spec.js
- test/unit/services/azurerediscache/index-spec.js
- test/unit/services/azurerediscache/poll-spec.js
- test/unittestlist.txt
From security review, we are asked to remove the credentials in the database. If they have to be stored for some particular reason, they need to be encrypted.
> Several fixes for security reasons.

- lib/services/azuresqldb/client.js
- lib/services/azuresqldb/cmd-provision.js
- test/unit/services/azuresqldb/provision-spec.js
…g server domain name in provision result
> add unit tests for the case not allow to create server and fix missing server domain name in provision result

- .travis.yml
- Dockerfile
- Makefile
- scripts/deploy.sh
Fixes #98 
This is a more tightly-scoped alternative to https://github.com/Azure/meta-azure-service-broker/pull/97
> dockerize the broker

- docs/azure-cosmos-db.md
- docs/how-admin-deploy-the-broker.md
- examples/cosmosdb-example-config.json
- lib/common/index.js
- lib/services/azurecosmosdb/client.js
- lib/services/azurecosmosdb/cmd-bind.js
- lib/services/azurecosmosdb/cmd-deprovision.js
- lib/services/azurecosmosdb/cmd-poll.js
- lib/services/azurecosmosdb/cmd-provision.js
- lib/services/azurecosmosdb/index.js
- lib/services/azurecosmosdb/service.json
- lib/services/azuredocdb/client.js
- package.json
- test/integration/lifecycle.js
- test/integration/submatrix/cosmosdb.js
- test/integration/test-matrix.js
- test/unit/services/azurecosmosdb/bind-spec.js
- test/unit/services/azurecosmosdb/deprovision-spec.js
- test/unit/services/azurecosmosdb/index-spec.js
- test/unit/services/azurecosmosdb/poll-spec.js
- test/unit/services/azurecosmosdb/provision-spec.js
- test/unit/services/azuredocdb/index-spec.js
- test/utils/azurecosmosdbClient.js
- test/utils/azuredocdbClient.js
- test/utils/clients.js
Cosmos DB: 
https://azure.microsoft.com/en-us/services/cosmos-db/
> Add module CosmosDB

- brokerserver.js
- docs/how-admin-deploy-the-broker.md
- lib/common/index.js
- lib/services/azurecosmosdb/index.js
- lib/services/azuredocdb/index.js
- lib/services/azuremysqldb/index.js
- lib/services/azurepostgresqldb/index.js
- lib/services/azurerediscache/index.js
- lib/services/azureservicebus/index.js
- lib/services/azuresqldb/index.js
- lib/services/azurestorage/index.js
- pcf-tile/tile.yml
- test/integration/submatrix/cosmosdb.js
- test/integration/submatrix/docdb.js
- test/integration/submatrix/mysqldb.js
- test/integration/submatrix/postgresqldb.js
- test/integration/submatrix/rediscache.js
- test/integration/submatrix/servicebus.js
- test/integration/submatrix/sqldb.js
- test/integration/submatrix/storage.js
- test/integration/test-matrix.js
- test/utils/azurecosmosdbClient.js
- test/utils/azuredocdbClient.js
- test/utils/azurerediscacheClient.js
- test/utils/azureservicebusClient.js
- test/utils/azuresqldbClient.js
- test/utils/azurestorageClient.js
- test/utils/supportedEnvironments.js
Solved https://github.com/Azure/meta-azure-service-broker/issues/117
> support to deploy on Azure USGov and German

- test/integration/submatrix/docdb.js
This commit is missing in previous PR: https://github.com/Azure/meta-azure-service-broker/pull/125
> fix location in docdb integration test

- docs/azure-event-hubs.md
- docs/azure-service-bus.md
- docs/how-admin-deploy-the-broker.md
- examples/eventhubs-example-config.json
- examples/servicebus-example-config.json
- lib/common/index.js
- lib/services/azureeventhubs/index.js
- lib/services/azureeventhubs/service.json
- lib/services/azureeventhubs/utils.js
- lib/services/azureservicebus/service.json
- manifest.yml
- package.json
- pcf-tile/tile.yml
- test/integration/submatrix/eventhubs.js
- test/integration/submatrix/servicebus.js
- test/integration/test-matrix.js
- test/unit/services/azureeventhubs/bind-spec.js
- test/unit/services/azureeventhubs/deprovision-spec.js
- test/unit/services/azureeventhubs/poll-spec.js
- test/unit/services/azureeventhubs/provision-spec.js
- test/unit/services/azureeventhubs/unbind-spec.js
- test/unit/services/azurerediscache/fixParameters-spec.js
- test/unit/services/azureservicebus/fixParameters-spec.js
- test/unit/services/azureservicebus/provision-spec.js
- test/utils/azureeventhubsClient.js
> separate event hubs from service bus module 

- lib/services/azuremysqldb/index.js
- lib/services/azuresqldb/index.js
Fix the same issue https://github.com/Azure/meta-azure-service-broker/issues/140 for MySQL DB and SQL DB module.
> fix uri encoding in mysqldb and sqldb binding credentials

- docs/how-admin-deploy-the-broker.md
1. add nodejs to the prerequisites
2. refine how to make plans public
> refine how-admin-deploy-the-broker.md

- docs/azure-mysql-db.md
- docs/azure-postgresql-db.md
- lib/services/azuremysqldb/index.js
- lib/services/azurepostgresqldb/index.js
https://github.com/Azure/meta-azure-service-broker/pull/142
1. update mysql/pgsql docs for the username and uri changes in credentials
2. fix username in mysql credentials
> Supplement PR142

- docs/migration/1.2.1_to_1.3.0_or_greater.js
- docs/migration/1.2.1_to_1.3.0_or_greater.md
Fixed https://github.com/Azure/meta-azure-service-broker/issues/154
> Add doc and script to fix upgrading issue from v1.2.1 to v1.3.0 or greater

- .jshintrc
- lib/broker/v2/api-handlers.js
- lib/common/index.js
- manifest.yml
- package.json
- pcf-tile/tile.yml
* Apply timingSafeEqual to basic authorization 
* Refine strong password generator
* Fixed https://github.com/Azure/meta-azure-service-broker/issues/151
> Fix offline dependency issue and security issues

- examples/rediscache-example-config.json
- lib/services/azurerediscache/cmd-provision.js
- lib/services/azurerediscache/service.json
- manifest.yml
- test/integration/submatrix/rediscache.js
Fix https://github.com/Azure/meta-azure-service-broker/issues/167.
> Use service plan to specify Redis SKU

- test/integration/lifecycle.js
revert to use _.each in lifecycle
> Fix lifecycle

- pcf-tile/generate-tile.sh
Add it to the tile generation script.
> Put .npmrc into the tile

- lib/common/index.js
- lib/services/azurepostgresqldb/cmd-provision.js
- lib/services/azurepostgresqldb/index.js
- lib/services/azurepostgresqldb/service.json
- test/integration/test-matrix.js
- test/utils/supportedEnvironments.js
This PR intends to fix #203 and #202:
- enable the PostgreSQL service on ChinaCloud
- update the PostgreSQL SKU list to include all new plans (General Purpose, Memory Optimized)
> Enable PostgreSQL on ChinaCloud, update SKU list

- README.md
- docs/how-to-tag-resources.md
* Added documentation on how to add custom tags to resources.
> docs: add custom tags to resources

- docs/azure-sql-db.md
Update Azure CLI 2.0 command on listing all Azure locations
> Update Azure command on listing locations
