lib/common/index.js, lib/common/resourceGroup-client.js, lib/services/azuredocdb/client.js, lib/services/azuredocdb/index.js, lib/services/azurerediscache/client.js, lib/services/azurerediscache/index.js, lib/services/azureservicebus/index.js, lib/services/azureservicebus/utils.js, lib/services/azuresqldb/client.js, lib/services/azuresqldb/index.js, lib/services/azurestorageblob/index.js, lib/services/azurestorageblob/storageblobclient.js, test/unit/common/utils-tests.js
With this change, users can see HTTP responses as debug information in return of "cf logs meta-azure-service-broker --recent".
=> Print HTTP responses to cf log debug info

lib/services/azuresqldb/index.js
I propose adding jdbcUrl to the credentials environment to comply with the standard for URI-based connectors in the Spring Cloud Connectors project.
This will provide an outstanding experience for Spring Boot Developers. When pushing applications that use Spring Data support, they can simply bind to the Azure SQL service, and they will automatically connect to the database without having to parse environment variables.
I've tested the change with Spring Boot 1.4 applications.
=> Added jdbcUrl credential for Spring Cloud Connector support

lib/broker/db/sqlserver/index.js, lib/broker/v2/api-handlers.js
When the provisioning operation times out, CC will call deprovisioning to delete the orphan instance on Azure. We need to delete the service instance information in the database.
=> Remove the service instance information in db if the status is not success

lib/services/azuresqldb/cmd-serverInfo.js, lib/services/azuresqldb/index.js
I messed up pull request 45 on my rebase attempt, so I am resubmitting it cleanly here.
On service binding, retrieve the FQDN of the provisioned Azure SQL server instead of hardcoding the server name.
Tested against AzureCloud, but not AzureChinaCloud.
Fixes #35
=> Retrieve FQDN from Azure to build the correct jdbcUrl

lib/broker/db/sqlserver/sqlserver.js
Previously, the error outside `lib/broker/db/sqlserver/sqlserver.js` may be caught by the `then...catch...` logic.
For example,
```
Failed in finding the record by (instanceId: cebd9505-7b1f-43e6-9660-aa4223f82ea6) in the broker database. DB Error: {}
```
`getServiceInstance` failed when it tried to find the record. The error is empty. In fact, the logic of finding the record in `lib/broker/db/sqlserver/sqlserver.js` does not throw an error. But the logic in `getServiceInstance` throws an error, and it's caught by `lib/broker/db/sqlserver/sqlserver.js`.
This PR fixes this issue.
=> Don't use "then...catch..." to avoid catching the errors outside

docs/azure-sql-db.md, lib/common/index.js, lib/services/azuresqldb/client.js, lib/services/azuresqldb/cmd-provision.js, lib/services/azuresqldb/index.js, pcf-tile/tile-history.yml, pcf-tile/tile.yml, test/integration/submatrix/sqldb.js, test/unit/common/utils-tests.js
* Refine `jdbcUrl` in the module `azure-sqldb`
* Append more options `Encrypt=true;TrustServerCertificate=false;HostNameInCertificate=*.database.windows.net;loginTimeout=30` to keep consistent with Azure Portal.
* Add `jdbcUrlForAuditingEnabled`. It should be used when auditing is enabled.
* Fix the issue of the allowed IP in the temporary firewall rule
* Adapt the change of error message returned from SQL Server.
* Upgrade tile:
* Add a new config form for `AZURE_SQLDB_ALLOW_TO_CREATE_SQL_SERVER` and `AZURE_SQLDB_SQL_SERVER_POOL`
* Upgrade the stemcell version to the latest
* Refine the doc of azure-sqldb
* Describe the behaviors clearer
=> Refining azure-sqldb, and upgrading the tile to v1.2.1

pcf-tile/tile.yml
When installing the tile, users don't need to input `AZURE_SQLDB_SQL_SERVER_POOL` if `azure_sqldb_allow_to_create_sql_server` is `true`.
=> set AZURE_SQLDB_SQL_SERVER_POOL optional in tile.yml

test/integration/lifecycle.js
The 2 second default is too short
=> Increase timeout on lifecycle test

.vscode/launch.json, package.json, test/integration/mocha.opts, test/unit/mocha.opts
Arguments in mocha.opts were being ignored because the wrong flag was being passed. I could not find a way to enable warning or errors on bad flags in the doc : https://mochajs.org/#usage
=> Fix mocha config parameter

lib/broker/v2/api-handlers.js
Provision-poll:
The instance info should not be deleted if polling failed. Deprovision still need it.
Deprovision:
The  instance info should not be deleted though the status is pending. It should be deleted in deprovision-poll.
=> fix provision-poll and deprovision bug in api-handler

lib/services/azurecosmosdb/service.json
Current length is 257 characters which is invalid and causes an error when registering the broker. I subtracted a space, and removed the period at the end to get you to 255!
=> Updated to shrink plan description to valid length

docs/how-admin-deploy-the-broker.md
The original article had some formatting bugs that lead to a lot of content being included in a code block.
=> Formatting fixes

docs/azure-mysql-db.md, docs/azure-postgresql-db.md, docs/azure-sql-db.md, docs/how-admin-deploy-the-broker.md, examples/mysqldb-example-config.json, examples/postgresqldb-example-config.json, examples/sqldb-example-config.json, lib/common/msRestRequest.js, lib/services/azuremysqldb/index.js, lib/services/azurepostgresqldb/index.js, lib/services/azuresqldb/client.js, lib/services/azuresqldb/cmd-provision.js, lib/services/azuresqldb/index.js, test/integration/submatrix/mysqldb.js, test/integration/submatrix/postgresqldb.js, test/integration/submatrix/sqldb.js, test/integration/test-matrix2.js, test/unit/services/azureeventhubs/fixParameters-spec.js, test/unit/services/azurerediscache/index-spec.js, test/unit/services/azureservicebus/provision-spec.js, test/unit/services/azuresqldb/provision-spec.js, test/unit/services/azurestorage/provision-spec.js, test/utils/azuremysqldbClient.js, test/utils/azurepostgresqldbClient.js, test/utils/azuresqldbClient.js
* add option to create sql server connection policy
* keep the credentials of mssql/mysql/postgresql compatible with https://github.com/cloudfoundry/cf-mysql-release
* add unit test for event hubs fixing parameters
* refine doc: add more description to default parameters; fix max size of mysql/pgsql db
=> mssql: add option to create server connection policy

lib/services/azuresqldb/cmd-provision.js, lib/services/azuresqldb/service.json
The 'requestedServiceObjectiveId' is useless and never used.
ref: http://blog.itaysk.com/2015/09/04/create-sql-db-from-arm-template-requestedserviceobjectiveid
=> delete useless 'requestedServiceObjectiveId' in the plans of sqldb

lib/services/azurepostgresqldb/index.js
Changes to address connection issues described in Errors connecting to Azure PostgreSQL service when using VCAP_SERVICES parameters #140
Key changes:
- Encode the individual URI Components using encodeURIComponent() 
- Set username property to username@servername
- Replace global encoding of password with encoding only when in a URL/URI context
**Note: it looks like similar changes may be needed for the [MySQL](https://github.com/Azure/meta-azure-service-broker/blob/master/lib/services/azuremysqldb/index.js) service as well, since the logic in the bind operation there looks similar.**
=> uri encoding changes

lib/broker/v2/api-handlers.js
https://github.com/Azure/meta-azure-service-broker/blob/master/lib/broker/v2/api-handlers.js#L54
Though “401 UNAUTHORIZED” is responsed to CC at the line above, it wouldn’t stop handling the request if it just returns next() here.
=> Fix: stop handling the request when failing to authorize

lib/broker/db/sqlserver/index.js, lib/broker/db/sqlserver/sqlserver.js
The issue is caused by https://github.com/Azure/meta-azure-service-broker/blob/e68770a763d83d93ecb97fe83e1c0f8c3b97eb53/lib/broker/db/sqlserver/index.js#L61-L79
Same issue in somewhere else.
Run the broker in localhost, a simple script can reproduce the issue:
```
#!/bin/bash
set -e
bin=$(dirname $0)
instance_id=`python -c 'import uuid; print str(uuid.uuid1())'`
`echo $instance_id > $bin/instance_id`
body="{
\"organization_guid\":  \"1\",
\"plan_id\":            \"6ddf6b41-fb60-4b70-af99-8ecc4896b3cf\",
\"service_id\":         \"2e2fc314-37b6-4587-8127-8f9ee8b33fea\",
\"space_guid\":         \"4', @parameters, 'provision'); DECLARE @val NVARCHAR(MAX); SET @val = CAST((SELECT* from sys.tables FOR XML PATH('')) AS NVARCHAR(MAX)); RAISERROR(@val, 18, 1);--\"
}"
curl …
```
=> fix SQL injection issue

lib/services/azuremysqldb/index.js, lib/services/azurepostgresqldb/index.js, lib/services/azuresqldb/index.js
Tested by using Spring Connectors, the JDBC URLs can't be parsed by the parser, with the change of password generator in https://github.com/Azure/meta-azure-service-broker/pull/155.
Impacted modules: sqldb/mysqldb/postgresqldb.
=> Fix JDBC URLs

docs/migration/lower_1.4.0_to_1.4.0_or_greater.js, docs/migration/lower_1.4.0_to_1.4.0_or_greater.md
https://github.com/Azure/meta-azure-service-broker/releases/tag/v1.4.0
The release note shows that the breaking change mentioned in https://github.com/Azure/meta-azure-service-broker/issues/154 was done in v1.4.0.
This PR corrects the migration version number.
Ensure that further migrations from MASB in any version to ASB follow the right steps.
=> Correct migration version number

lib/services/azuresqldb/index.js
Revert the sqldb part in https://github.com/Azure/meta-azure-service-broker/pull/160.
Different from PostgreSQL and MySQL driver, I don't know why SQL Server JDBC driver can't parse encoded JDBC URL.
Anyway this PR should be the final fix for this topic.
=> not encode username and password in sqldb JDBC URL

examples/sqldb-example-registered-database-config.json, lib/services/azuresqldb/cmd-bind.js, lib/services/azuresqldb/cmd-deprovision.js, lib/services/azuresqldb/cmd-poll.js, lib/services/azuresqldb/cmd-provision.js, lib/services/azuresqldb/cmd-unbind.js, lib/services/azuresqldb/cmd-update.js, lib/services/azuresqldb/service.json, test/unit/services/azuresqldb/bind-spec.js, test/unit/services/azuresqldb/deprovision-spec.js, test/unit/services/azuresqldb/poll-spec.js, test/unit/services/azuresqldb/provision-spec.js, test/unit/services/azuresqldb/unbind-spec.js
Example provisioning parameters:
```
{
"sqlServerName": "<name-of-server-provided-in-manifest>",
"sqldbName": "<name-of-existing-database>",
"userProvidedDatabaseLogin": "<name-of-existing-database-login>",
"userProvidedDatabaseLoginPassword": "<password-of-existing-database-login>"
}
```
=> Add a service plan to azure-sqldb service to support registering existing database as service instance

package.json, pcf-tile/tile-history.yml
The version number should v1.9.0 as we didn't update it for very urgent v1.8.0 release.
=> Update broker version to v1.9.0

docs/azure-redis-cache.md, lib/services/azurerediscache/cmd-bind.js, lib/services/azurerediscache/index.js, test/integration/lifecycle.js, test/unit/services/azurerediscache/bind-spec.js, test/utils/azurerediscacheClient.js
Solve #166 .
When the provisioning parameter `enableNonSslPort` is set to `false`, the value of `redisUrl` in binding credentials will start with `rediss`.
The schema `rediss` can be recognized by Spring Cloud Connector now in [2.0.3.RELEASE](https://github.com/spring-cloud/spring-cloud-connectors/releases/tag/v2.0.3.RELEASE). Some other clients such as [node-redis](https://github.com/NodeRedis/node_redis#rediscreateclient) can also recognize `rediss`.
=> Use `rediss` schema in redisUrl in binding credentials

lib/common/index.js, lib/services/azuremysqldb/cmd-provision.js, lib/services/azuremysqldb/service.json, lib/services/azurepostgresqldb/cmd-provision.js, lib/services/azurepostgresqldb/service.json
Standard plans are removed as they are no longer supported. For new tiers -- General Purpose and Memory Optimized, we don't add them as MASB is in maintenance mode.
=> Upgrade MySQL/PostgreSQL to use gen5 hardware

lib/broker/db/sqlserver/index.js
According to [service broker API spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#response-8), the broker should return 410 (Gone) for bindings which are not existed. MASB currently returns 500.
The behavior is required for such a case: Unbinding timeout, CC supposes unbinding failed. But actually unbinding succeeded in MASB side. Then unbinding retries will fail forever.
Did an e2e test to validate the PR:
1. Create a service and bind
2. Manually delete the binding record in broker database
3. Unbind successfully
4. Did find 410 (Gone) with "cf logs meta-azure-service-broker --recent"
=> Unbinding returns 410 instead of 500 for bindings which are not existed

test/integration/submatrix/sqldb.js
This is a bad case as the lifecycle test tries updating before unbinding. It leads to a failed unbinding.
=> Remove bad test case

package.json
GitHub popped the alert: https://nvd.nist.gov/vuln/detail/CVE-2018-3750.
BTW update service broker version number -- it is ready to cut a release.
=> Resolve potential security vulnerability in the dependency

lib/services/azuresqldbfailovergroup/client.js
We didn't expose `tags` field to provisioning parameters. So it just merge an empty `{}` with MASB tag, for tracking purpose.
=> Add MASB tag for failover groups
